--------------------------------------------------------
--  Fichier créé - mardi-février-24-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "PROJET1"."CLIENTS" 
   (	"ID_CLIENTS" NUMBER, 
	"NOM_CLIENTS" VARCHAR2(20 BYTE), 
	"PRÉNOM_CLIENTS" VARCHAR2(20 BYTE), 
	"TELEPHONE_CLIENTS" NUMBER, 
	"MAIL_CLIENTS" VARCHAR2(20 BYTE), 
	"DATE_CLIENTS" DATE, 
	"STATUT_CLIENTS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJET1.CLIENTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET1"."CLIENTS_PK" ON "PROJET1"."CLIENTS" ("ID_CLIENTS", "NOM_CLIENTS", "PRÉNOM_CLIENTS", "TELEPHONE_CLIENTS", "MAIL_CLIENTS", "DATE_CLIENTS", "STATUT_CLIENTS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "PROJET1"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("ID_CLIENTS", "NOM_CLIENTS", "PRÉNOM_CLIENTS", "TELEPHONE_CLIENTS", "MAIL_CLIENTS", "DATE_CLIENTS", "STATUT_CLIENTS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET1"."CLIENTS" MODIFY ("STATUT_CLIENTS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."CLIENTS" MODIFY ("DATE_CLIENTS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."CLIENTS" MODIFY ("MAIL_CLIENTS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."CLIENTS" MODIFY ("TELEPHONE_CLIENTS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."CLIENTS" MODIFY ("PRÉNOM_CLIENTS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."CLIENTS" MODIFY ("NOM_CLIENTS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."CLIENTS" MODIFY ("ID_CLIENTS" NOT NULL ENABLE);
