--------------------------------------------------------
--  Fichier créé - mardi-février-24-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "PROJET1"."COMMANDE" 
   (	"ID_COMMANDE" NUMBER, 
	"PRODUIT_COMMANDE" VARCHAR2(100 BYTE), 
	"QUANTITÉ_COMMANDE" NUMBER(20,0), 
	"PRIX_UNITAIRE_COMMANDE" NUMBER(20,2), 
	"TOTAL_COMMANDE" NUMBER(20,2), 
	"DATE_COMMANDE" DATE, 
	"DATE_LIVRAISON_COMMANDE" DATE, 
	"MODE_PAIEMENT_COMMANDE" VARCHAR2(30 BYTE), 
	"STATUT_COMMANDE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJET1.COMMANDE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007380
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET1"."SYS_C007380" ON "PROJET1"."COMMANDE" ("ID_COMMANDE", "PRODUIT_COMMANDE", "QUANTITÉ_COMMANDE", "PRIX_UNITAIRE_COMMANDE", "TOTAL_COMMANDE", "DATE_COMMANDE", "DATE_LIVRAISON_COMMANDE", "MODE_PAIEMENT_COMMANDE", "STATUT_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "PROJET1"."COMMANDE" ADD CONSTRAINT "SYS_C007380" PRIMARY KEY ("ID_COMMANDE", "PRODUIT_COMMANDE", "QUANTITÉ_COMMANDE", "PRIX_UNITAIRE_COMMANDE", "TOTAL_COMMANDE", "DATE_COMMANDE", "DATE_LIVRAISON_COMMANDE", "MODE_PAIEMENT_COMMANDE", "STATUT_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET1"."COMMANDE" MODIFY ("STATUT_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."COMMANDE" MODIFY ("MODE_PAIEMENT_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."COMMANDE" MODIFY ("DATE_LIVRAISON_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."COMMANDE" MODIFY ("TOTAL_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."COMMANDE" MODIFY ("DATE_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."COMMANDE" MODIFY ("PRIX_UNITAIRE_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."COMMANDE" MODIFY ("QUANTITÉ_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."COMMANDE" MODIFY ("PRODUIT_COMMANDE" NOT NULL ENABLE);
