--------------------------------------------------------
--  Fichier créé - mardi-février-24-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "PROJET1"."FOURNISSEURS" 
   (	"ID_FOURNISSEURS" NUMBER, 
	"NOM_FOURNISSEURS" VARCHAR2(50 BYTE), 
	"PRÉNOM_FOURNISSEURS" VARCHAR2(50 BYTE), 
	"MAIL_FOURNISSEURS" VARCHAR2(50 BYTE), 
	"ADRESSSE_FOURNISSEURS" VARCHAR2(50 BYTE), 
	"TEL_FOURNISSEURS" NUMBER, 
	"QUANTITÉ_FOURNISSEURS" NUMBER, 
	"TYPE_FOURNISSEURS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJET1.FOURNISSEURS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FOURNISSEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET1"."FOURNISSEURS_PK" ON "PROJET1"."FOURNISSEURS" ("ID_FOURNISSEURS", "NOM_FOURNISSEURS", "PRÉNOM_FOURNISSEURS", "MAIL_FOURNISSEURS", "ADRESSSE_FOURNISSEURS", "TEL_FOURNISSEURS", "QUANTITÉ_FOURNISSEURS", "TYPE_FOURNISSEURS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "PROJET1"."FOURNISSEURS" ADD CONSTRAINT "FOURNISSEURS_PK" PRIMARY KEY ("ID_FOURNISSEURS", "NOM_FOURNISSEURS", "PRÉNOM_FOURNISSEURS", "MAIL_FOURNISSEURS", "ADRESSSE_FOURNISSEURS", "TEL_FOURNISSEURS", "QUANTITÉ_FOURNISSEURS", "TYPE_FOURNISSEURS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET1"."FOURNISSEURS" MODIFY ("TYPE_FOURNISSEURS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."FOURNISSEURS" MODIFY ("QUANTITÉ_FOURNISSEURS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."FOURNISSEURS" MODIFY ("TEL_FOURNISSEURS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."FOURNISSEURS" MODIFY ("ADRESSSE_FOURNISSEURS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."FOURNISSEURS" MODIFY ("MAIL_FOURNISSEURS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."FOURNISSEURS" MODIFY ("PRÉNOM_FOURNISSEURS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."FOURNISSEURS" MODIFY ("NOM_FOURNISSEURS" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."FOURNISSEURS" MODIFY ("ID_FOURNISSEURS" NOT NULL ENABLE);
