--------------------------------------------------------
--  Fichier créé - mardi-février-24-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MATERIAUX
--------------------------------------------------------

  CREATE TABLE "PROJET1"."MATERIAUX" 
   (	"ID_MATERIAUX" NUMBER, 
	"TYPE_MATERIAUX" VARCHAR2(50 BYTE), 
	"QUANTITÉ_MATERIAUX" VARCHAR2(50 BYTE), 
	"SEUIL_MATERIAUX" VARCHAR2(50 BYTE), 
	"FOURNISSEUR_MATERIAUX" VARCHAR2(50 BYTE), 
	"NOM_MATERIAUX" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJET1.MATERIAUX
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MATERIAUX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET1"."MATERIAUX_PK" ON "PROJET1"."MATERIAUX" ("ID_MATERIAUX", "NOM_MATERIAUX", "TYPE_MATERIAUX", "QUANTITÉ_MATERIAUX", "SEUIL_MATERIAUX", "FOURNISSEUR_MATERIAUX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MATERIAUX
--------------------------------------------------------

  ALTER TABLE "PROJET1"."MATERIAUX" ADD CONSTRAINT "MATERIAUX_PK" PRIMARY KEY ("ID_MATERIAUX", "NOM_MATERIAUX", "TYPE_MATERIAUX", "QUANTITÉ_MATERIAUX", "SEUIL_MATERIAUX", "FOURNISSEUR_MATERIAUX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJET1"."MATERIAUX" MODIFY ("NOM_MATERIAUX" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."MATERIAUX" MODIFY ("FOURNISSEUR_MATERIAUX" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."MATERIAUX" MODIFY ("SEUIL_MATERIAUX" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."MATERIAUX" MODIFY ("QUANTITÉ_MATERIAUX" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."MATERIAUX" MODIFY ("TYPE_MATERIAUX" NOT NULL ENABLE);
  ALTER TABLE "PROJET1"."MATERIAUX" MODIFY ("ID_MATERIAUX" NOT NULL ENABLE);
