--------------------------------------------------------
--  Fichier créé - mercredi-avril-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PROJET1"."USERS" 
   (	"ID_USER" NUMBER, 
	"NOM" VARCHAR2(100) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(100) NOT NULL ENABLE, 
	"TEL" VARCHAR2(20), 
	"MAIL" VARCHAR2(150), 
	"MDP" VARCHAR2(255) NOT NULL ENABLE, 
	"SALAIRE" NUMBER(10,2), 
	"ROLE" VARCHAR2(50), 
	"ETAT" VARCHAR2(20), 
	 PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "CHK_USERS_ETAT" CHECK (etat IN ('Actif','Inactif')) ENABLE, 
	 CONSTRAINT "USERS_ETAT_CHK" CHECK (ETAT IN ('Actif','Inactif')) ENABLE, 
	 CONSTRAINT "USERS_ROLE_CHK" CHECK (ROLE IN (
  'Responsable client',
  'Responsable materiaux',
  'Responsable achats',
  'Responsable commandes',
  'Ouvrier'
)) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into PROJET1.USERS
SET DEFINE OFF;
Insert into PROJET1.USERS (ID_USER,NOM,PRENOM,TEL,MAIL,MDP,SALAIRE,ROLE,ETAT) values ('1','youssef','khirji','11110000','youssef@gmail.com','e76923958881233eb9fc232106d60686be0488a99e54976c35280df20f713be9$64a622dfaec04da1','1500','Responsable client','Actif');
--------------------------------------------------------
--  DDL for Index SYS_C007195
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET1"."SYS_C007195" ON "PROJET1"."USERS" ("ID_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007196
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET1"."SYS_C007196" ON "PROJET1"."USERS" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PROJET1"."USERS" ADD CONSTRAINT "USERS_ROLE_CHK" CHECK (ROLE IN (
  'Responsable client',
  'Responsable materiaux',
  'Responsable achats',
  'Responsable commandes',
  'Ouvrier'
)) ENABLE
  ALTER TABLE "PROJET1"."USERS" ADD CONSTRAINT "USERS_ETAT_CHK" CHECK (ETAT IN ('Actif','Inactif')) ENABLE
  ALTER TABLE "PROJET1"."USERS" ADD CONSTRAINT "CHK_USERS_ETAT" CHECK (etat IN ('Actif','Inactif')) ENABLE
  ALTER TABLE "PROJET1"."USERS" ADD UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJET1"."USERS" ADD PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJET1"."USERS" MODIFY ("MDP" NOT NULL ENABLE)
  ALTER TABLE "PROJET1"."USERS" MODIFY ("PRENOM" NOT NULL ENABLE)
  ALTER TABLE "PROJET1"."USERS" MODIFY ("NOM" NOT NULL ENABLE)
